### PR TITLE
Add implementations for Nicira Extension: TLVMap and NXController

### PR DESCRIPTION
**Pull request by wenyingd**
1. tlv-map is used to set Geneve header. Add Nicira extension messages to
   get or modify tlv-map.
2. Add implementations to support Nicira extension: Set_Controller_ID and
   NXController.
3. Rename BundleError as VendorError.
4. Expand VendorHeader to support adding Vendor data in the message.
5. Use VendorHeader to send Bundle messages.
6. Expose data in Uint32Message and Uint16Message as public.

### CODE REVIEW

**Comment by jojimt** [comment]
Please address the test failures and then I'll review.

**Comment by wenyingd** [comment]
> Please address the test failures and then I'll review.

Sure, I will update the failure.

**Comment by wenyingd** [comment]
Hi @jojimt , I have updated to fix the check failure, could you help give a review?

**Review by jojimt — APPROVED** [review]
LGTM

**Pull request merged**
